server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9420

logging:
  level: INFO
  loggers:
    "com.kainos": DEBUG

applicationConfig:
  applicationVersionFilePath:

privateKey: YOUR_PRIVATE_KEY
url: ROOT_URL_TO_GITLAB